---
name: Changes Comparison

# Trigger: PR must be opened or reopened.
on:
  pull_request:
    types: [opened, reopened]

# If trigger, do:
jobs:

  # Job #1 - Retrieve metadata and save it in env files.
  upload-artifacts:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Scrape HEADs
        shell: bash
        
        # Scrape repository secrets and setup environment variables.
        env:
          USERNAME: $ {{ secrets.AUTH_UNAME }}
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}
          
        # Get open requests' and the trigger request's HEADs and save them in env files.
        run: |
          # Clear open_prs
          echo "" > open_prs.txt
          
          printf "Scraping open PR HEADs "
          # Get open PRs' HEADs
          if open_request_ids=`curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
            | jq -r .[].head.sha`; then
            echo
            
          fi
          
          if open_request_names=`curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
            | jq -r .[].head.ref`; then
          fi
          
          if open_request_urls=`curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
            | jq -r .[].url`; then
          fi

          length=${#open_request_urls[@]}
          for ((x=0; x == $length ; x++)); do
            name=${open_request_names[x]}
            head=${open_request_ids[x]}
            url=${open_request_urls[x]}3
            data_json=$(jq -n --arg head "$head" --arg url "$url" --arg name $"name" \
            '{name: $name,head: $head, url: $url}')
            echo "$data_json" >> open_prs.txt
          
        # Upload the env files. name is ID. Must match downloads.
      - name: upload open PR commit HEADs
        uses: actions/upload-artifact@v4
        with:
          name: open_prs
          path: open_prs.txt
          
      

  # job #2 - Download the artifacts and use the data to compare changes between potentially divergent branches.
  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    
    name: Compare Changes
    steps:
        # Get the repository,
      - name: Get Repository
        uses: actions/checkout@v4
        
        # Sign in with username and email, rebase local branch and checkout to main,
        # Necessary to access the repository.
      - name: Pull Latest Changes
        shell: bash
        run: |
          git config --global user.email ${{ secrets.AUTH_EMAIL }}
          git config --global user.name ${{ secrets.AUTH_UNAME }}
          git config pull.rebase true
          git pull origin main
          git checkout main
        # Ensure this step finished successfully before continuing,
        # Else end task.
        if: ${{ success() }}
          
        # Download artifacts. Must execute after checkout.
      - name: Retrieve Open PR's
        uses: actions/download-artifact@v4
        with:
          # Must match
          name: open_prs
      
        # Scrape repository secrets and setup environment variables.
      - shell: bash
        name: Compare Changes
        env:
          USERNAME: ${{ secrets.AUTH_UNAME }}
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        # Iterate through open PR commits and compare changes between
        # The trigger commit and other PR commits.
        run: |
          successful_rebases=("*`echo "main"`* -> \n")
          # Update repository after downloading artifacts
          git pull
          if [ -e "open_prs.txt" ]; then
            # Iterate through open PR commit HEADs
            while IFS= read -r line; do
              # First line is empty. If empty, continue
              if [ -z "$line" ]; then
                continue
              else
                branch_name=`git branch -r --contains "${line}"`
                git rebase "$line"|| { \
                curl -H "Content-Type: application/json" -X POST -d \
                '{"username": "Conflict Seeker", "content": "'"**[CONFLICTING VERSIONS FOUND]** \n\n**Rebase Order:** \n ${successful_rebases} \n **Conflict occurred** while rebasing ${line} (`echo ${branch_name}`)"'"}' \
                "${WEBHOOK}"; 
                exit 1;
                }
                successful_rebases+="*`echo ${line}`* (`echo ${branch_name}`)-> \n";
              fi
            done < open_prs.txt
          else
            echo "No open_prs.txt in directory"
            exit 1
          fi
...
