---
name: Artifact tests
on:
  push:

jobs:
  upload-artifacts:
    name: keke
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          USERNAME: "Ryboster"
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}
        run: |
          open_request_ids=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
          | jq -r .[].head.sha`
          for id in $open_request_ids
          do
            echo $id >> open_prs.txt
          done
      - name: uploadme
        uses: actions/upload-artifact@v4
        with:
          name: open_prs
          path: open_prs.txt

  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    name: downloadme
    steps:
      - name: downloading
        uses: actions/download-artifact@v4
        with:
          name: test_artifact
      - shell: bash
        run: |
          while IFS= read -r line; do
            echo $line
          done < open_prs.txt
...
