---
name: Artifact tests
on:
  push:

jobs:
  upload-artifacts:
    name: keke
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo value1 > art1.txt
      - name: uploadme
        uses: actions/upload-artifact@v4
        with:
          name: art1
          path: art1.txt

  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    name: downloadme
    steps:
      - name: downloading
        uses: actions/download-artifact@v4
        with:
          name: art1
          
      - shell: bash
        run: |
          value=`cat art1.txt`
          echo $value
...
