---
name: Automatic Diversion Resolution
on:
  pull_request:
    types: [opened]

jobs:
  update:
    runs-on: ubuntu-22.04
    name: Diversion Test

    steps:
      - name: Testing different environments ...

        env:
          USERNAME: "Ryboster"
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}
          

        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls\
          | jq '.[].links'
...
