---
name: Automatic Diversion Resolution
on:
  pull_request:
    types: [opened, reopened]

jobs:
  update:
    runs-on: ubuntu-22.04
    name: Diversion Test

    steps:
      - name: Testing different environments ...

        env:
          USERNAME: "Ryboster"
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}

        run: |
          x=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
          | jq -r .[].head.sha`
          for y in $x
          do
            echo $y
          done
          
          pull_request_url=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
          commit_id=$(curl -L \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          "$pull_request_url" \
          | jq -r '.head.sha')
          echo $commit_id
...
