---
name: Testmepls
on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      open_request_ids: ${{ steps.fetch.outputs.open_request_ids }}
      
    env:
      USERNAME: "Ryboster"
      TOKEN: ${{ secrets.SECRET_TOKEN }}
      REPO: ${{ secrets.REPO }}
      OWNER: ${{ secrets.OWNER }}

    steps:
      - name: Fetch Variables
        id:  fetch
        run: |
          open_request_ids=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
          | jq -r .[].head.sha` 
          echo "open_request_ids=${open_request_ids}" >> "$GITHUB_ENV"

  job2:
    needs: setup
    runs-on: ubuntu-latest
    env:
      USERNAME: "Ryboster"
      TOKEN: ${{ secrets.SECRET_TOKEN }}
      REPO: ${{ secrets.REPO }}
      OWNER: ${{ secrets.OWNER }}
    steps:
      - name: Print me
        run: |
          echo $open_request_ids
          echo ${{ env.USERNAME }}
          echo ${{ env.OWNER }}
          echo ${{ env.REPO }}
...
