---
name: Artifact tests
on:
  pull_request:
    types: [opened, reopened]

jobs:
  upload-artifacts:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get variables
        shell: bash

        env:
          USERNAME: "Ryboster"
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}
        run: |
          
          echo "" > open_prs.txt
          open_request_ids=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
          | jq -r .[].head.sha`
          
          for id in $open_request_ids
          do
            echo "${id}" >> open_prs.txt
          done
          echo .pull_request
          
          pull_request_url=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
          commit_id=$(curl -L \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          "$pull_request_url" \
          | jq -r '.head.sha')
          
          echo "{$commit_id}"
          echo "${commit_id}"
          echo $commit_id
          echo "$commit_id" > commit_id.txt

      - name: upload open PR's
        uses: actions/upload-artifact@v4
        with:
          name: open_prs
          path: open_prs.txt
          
      - name: upload variables
        uses: actions/upload-artifact@v4
        with:
          name: commit_id
          path: commit_id.txt



  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    name: download
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Pull latest changes
        shell: bash
        run: |
          touch k
          git config --global user.email "kakashise@o2.pl"
          git config --global user.name "Ryboster"
          git config pull.rebase true
          git status
          git pull origin main
          git checkout main
          git status
      - name: Retrieve open PR's
        uses: actions/download-artifact@v4
        with:
          name: open_prs # must match the name of artifact
      - name: Retrieve commit ID
        uses: actions/download-artifact@v4
        with:
          name: commit_id
      - shell: bash
        name: Print me
        env:
          USERNAME: "Ryboster"
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}
        run: |
          git fetch https://${{ env.TOKEN }}@github.com/${{ env.OWNER }}/${{ env.REPO }}.git
          git status
          git checkout main
          git pull
          while IFS= read -r line; do
            if [ -z "$line" ]; then
              continue
            fi
            echo "Comparing $(cat commit_id.txt) to commit: $line"
            if [ "$(cat commit_id.txt)" != "$line" ]; then
              git diff "$line" "$(cat commit_id.txt)"
            else
              echo "cant compare self"
            fi
          done < open_prs.txt
...
