---
name: Automatic Diversion Resolution
on:
  pull_request:
    types: [opened, reopened]

jobs:
  update:
    runs-on: ubuntu-22.04
    name: Diversion Test

    steps:
      - name: Testing different environments ...

        env:
          USERNAME: "Ryboster"
          TOKEN: ${{ secrets.SECRET_TOKEN }}
          REPO: ${{ secrets.REPO }}
          OWNER: ${{ secrets.OWNER }}

        run: |
          open_request_ids=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
          | jq -r .[].head.sha`
          
          echo "Scraped IDs:"
          for id in $open_request_ids
          do
            echo $id
          done
          
          pull_request_url=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
          commit_id=$(curl -L \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          "$pull_request_url" \
          | jq -r '.head.sha')
          echo $commit_id
          
          for id in $open_request_ids
          do
            echo "iterating through: "
            echo $id
            echo "comparing to: "
            echo $commit_id
            if [ "$commit_id" != "$id"; then
              git diff $commit_id $id
              echo "comparing id"
              echo $id
              echo "to"
              echo $commit_id
            else
              echo "cannot compare branch to itself"
            fi
          done
...
