---
name: Artifact tests
on:
  push:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p /artifacts/
      - run: echo "value1" > /artifacts/art1.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /artifacts/art1.txt
          
  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download an artifact
        uses: actions/download-artifact@v4
        with:
          name: downloadme
        run: |
          value=`cat /artifacts/art1.txt`
          echo $value
...
