---
name: Artifact tests
on:
  push:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    uses: actions/upload-artifact@v4
    steps:
      - run: mkdir -p /artifacts/
      - run: echo "value1" > art1.txt
        with:
          name: my-artifact
          path: art1.txt
          
  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    uses: actions/download-artifact@v4
    steps:
      - name: Download an artifact
        with:
          name: downloadme
        run: |
          value=`cat art1.txt`
          echo $value
...
